spring:
  application:
     name: UserManagement

  datasource:
    url: jdbc:oracle:thin:@//localhost:58108/XEPDB1
    username: oracle
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
           dialect: org.hibernate.dialect.OracleDialect
default:
   admin:
     email: karani.maina2010@gmail.com
redis:
  host: localhost
  port: 6379
    #spring.mail.host= 10.1.1.213
    #spring.mail.port= 25
    #spring.mail.username= mbanking@postbank.co.ke
    #spring.mail.password= opengates123!
    #spring.mail.properties.mail.smtp.auth= false
    #spring.mail.properties.mail.smtp.starttls.enable= false
management:
  endpoints:
   web:
     exposure:
      include: '*'
  endpoint:
    health:
     show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
eureka:
  client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
      defaultZone: http://localhost:9713/eureka/
   hostname: localhost
app:
  keystore:
   name: keystore.jks
   password: Pass@Word
   alias: myalias
